In [1]:
from types import SimpleNamespace
import numpy as np
import bisect
a = np.array([[np.nan, np.nan, np.nan, np.nan, 1],[np.nan, 1, 1, 3, np.nan], [np.nan, 1, 2, 3, np.nan], [np.nan, np.nan, np.nan, np.nan, np.nan]])

data = a
display(data)

self = SimpleNamespace()
self.h_split = 2
self.v_split = 2

array([[nan, nan, nan, nan,  1.],
       [nan,  1.,  1.,  3., nan],
       [nan,  1.,  2.,  3., nan],
       [nan, nan, nan, nan, nan]])

In [9]:
is_numeric = ~np.isnan(data)
is_numeric[:]

array([[False, False, False, False,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [4]:
numeric_cols = (~np.isnan(data)).sum(0)
cols_with_numbers = np.argwhere(numeric_cols > 0)
first_col_with_number = cols_with_numbers.min()
last_col_with_numer = cols_with_numbers.max()

n_columns = last_col_with_numer - first_col_with_number + 1

n_columns_per_group = n_columns / self.h_split

display(numeric_cols, cols_with_numbers, first_col_with_number, last_col_with_numer)

col_splits = [
    first_col_with_number + bisect.bisect_left(np.arange(n_columns), c * n_columns_per_group)
    for c in range(0, self.h_split)
] + [last_col_with_numer+1]

col_splits



array([0, 2, 2, 2, 1])

array([[1],
       [2],
       [3],
       [4]])

1

4

[1, 3, 5]

In [112]:
A  = ~np.isnan(data)
A

array([[False, False, False, False,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [113]:
import itertools
for splits in itertools.pairwise(col_splits):
    matrix = A.copy()
    matrix[:, :splits[0]] = False
    matrix[:, splits[1]:] = False
    display(matrix)

array([[False, False, False, False, False],
       [False,  True,  True, False, False],
       [False,  True,  True, False, False],
       [False, False, False, False, False]])

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False,  True, False],
       [False, False, False, False, False]])

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [87]:
col_splits

[0, 2]

In [37]:
# Test how to stack the resulting matrices, and check whether every cell is represented once

from eitprocessing.roi_selection.gridselection import GridSelection
import numpy as np

g = GridSelection(3, 4, False)
data = np.full((32, 32), 1)

matrices = g.find_grid(data)
np.array_equal(np.sum(np.stack(matrices, axis=-1), axis=-1), np.ones(data.shape))

True

In [35]:
# Test way to parse string to True/False matrix

result = 'TFF,FTF,FFT;TF,FT'
array = [np.array([tuple(row) for row in matrix.split(',')]) == 'T' for matrix in result.split(';')] 
array

[array([[ True, False, False],
        [False,  True, False],
        [False, False,  True]]),
 array([[ True, False],
        [False,  True]])]

In [33]:
# Test way to create a layout map of the returned matrices

v_split = 3
h_split = 4
n_groups = v_split * h_split
np.reshape(np.arange(n_groups), (v_split, h_split))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])